import type { GameplayConfig, GameplayConfigId } from '../../../types/gameplay';

/*** Define reusable gameplay tuning presets that rounds reference by id. */
export const GAMEPLAY_CONFIGS = {
  starter: {
    resolutionFeedbackMs: 850,
    correctFeedbackVisibleMs: 2500,
    mistakeVisibleMs: 420,
    shotVisibleMs: 220,
    startingHealth: 5,
    maxHealth: 7,
    correctActionsPerExtraLife: 10,
    wrongActionDamage: 1,
    projectileDamage: 1,
    roundTargetCount: 20,
    initialCreatureCount: 6,
    activeTargetCount: 2,
    creatureMinimumDistancePercent: 18,
    movementZoneStartPercent: 65,
    playerMinXPercent: 9,
    playerMaxXPercent: 91,
    playerStartXPercent: 50,
    keyboardStepPercent: 5,
    projectileBaseDurationMs: 3400,
    projectileDurationStepMs: 260,
    projectileDelayStepMs: 70,
    projectileLetterSpacingPercent: 2.2,
    playerLaneYPercent: 86,
    projectileFallDistancePercent: 110,
    projectileMinImpactProgress: 0.16,
    projectileMaxImpactProgress: 0.82,
    projectileMinXPercent: 6,
    projectileMaxXPercent: 94,
    projectileNearDriftPercent: 7,
    projectileFarDriftPercent: 14,
    invulnerabilityMs: 1800,
    levelCompleteVisibleMs: 1200,
    rewardParticleCount: 8,
    hitStopMs: 320,
    playerRespawnDelayMs: 520,
    playerRespawnBlinkMs: 900,
  },
} satisfies Record<GameplayConfigId, GameplayConfig>;
