import type { LevelDefinition } from '../../../types/gameplay';

export const FIRST_LEVEL: LevelDefinition = {
  id: 'animals-1',
  number: 1,
  title: 'ANIMALES',
  targetCategory: 'animals',
  targetCount: 20,
  initialCreatures: [
    {
      id: 'creature-gato',
      word: { id: 'gato', text: 'gato', categories: ['animals'] },
      xPercent: 18,
      yPercent: 25,
      variant: 'mint',
      motion: 'bob',
      animationDelaySeconds: -1.2,
      animationDurationSeconds: 5.8,
    },
    {
      id: 'creature-mesa',
      word: { id: 'mesa', text: 'mesa', categories: ['home'] },
      xPercent: 57,
      yPercent: 19,
      variant: 'berry',
      motion: 'sway',
      animationDelaySeconds: -2.1,
      animationDurationSeconds: 7.2,
    },
    {
      id: 'creature-perro',
      word: { id: 'perro', text: 'perro', categories: ['animals'] },
      xPercent: 79,
      yPercent: 34,
      variant: 'sun',
      motion: 'drift',
      animationDelaySeconds: -0.8,
      animationDurationSeconds: 6.7,
    },
    {
      id: 'creature-caballo',
      word: { id: 'caballo', text: 'caballo', categories: ['animals'] },
      xPercent: 31,
      yPercent: 49,
      variant: 'lavender',
      motion: 'drift',
      animationDelaySeconds: -3.4,
      animationDurationSeconds: 7.6,
    },
    {
      id: 'creature-coche',
      word: { id: 'coche', text: 'coche', categories: ['transport'] },
      xPercent: 68,
      yPercent: 55,
      variant: 'mint',
      motion: 'bob',
      animationDelaySeconds: -2.8,
      animationDurationSeconds: 6.1,
    },
    {
      id: 'creature-pajaro',
      word: { id: 'pajaro', text: 'pájaro', categories: ['animals'] },
      xPercent: 43,
      yPercent: 67,
      variant: 'berry',
      motion: 'sway',
      animationDelaySeconds: -1.7,
      animationDurationSeconds: 7.9,
    },
  ],
  respawnCreatures: [
    {
      id: 'spawn-conejo',
      word: { id: 'conejo', text: 'conejo', categories: ['animals'] },
      xPercent: 22,
      yPercent: 31,
      variant: 'lavender',
      motion: 'bob',
      animationDelaySeconds: -1.1,
      animationDurationSeconds: 6.8,
    },
    {
      id: 'spawn-silla',
      word: { id: 'silla', text: 'silla', categories: ['home'] },
      xPercent: 72,
      yPercent: 24,
      variant: 'sun',
      motion: 'sway',
      animationDelaySeconds: -2.2,
      animationDurationSeconds: 7.4,
    },
    {
      id: 'spawn-pez',
      word: { id: 'pez', text: 'pez', categories: ['animals'] },
      xPercent: 48,
      yPercent: 42,
      variant: 'mint',
      motion: 'drift',
      animationDelaySeconds: -0.7,
      animationDurationSeconds: 6.2,
    },
    {
      id: 'spawn-pan',
      word: { id: 'pan', text: 'pan', categories: ['food'] },
      xPercent: 81,
      yPercent: 52,
      variant: 'berry',
      motion: 'bob',
      animationDelaySeconds: -1.8,
      animationDurationSeconds: 5.9,
    },
    {
      id: 'spawn-tortuga',
      word: { id: 'tortuga', text: 'tortuga', categories: ['animals'] },
      xPercent: 29,
      yPercent: 58,
      variant: 'sun',
      motion: 'sway',
      animationDelaySeconds: -3,
      animationDurationSeconds: 8.1,
    },
    {
      id: 'spawn-tren',
      word: { id: 'tren', text: 'tren', categories: ['transport'] },
      xPercent: 59,
      yPercent: 63,
      variant: 'lavender',
      motion: 'drift',
      animationDelaySeconds: -2.5,
      animationDurationSeconds: 7,
    },
    {
      id: 'spawn-vaca',
      word: { id: 'vaca', text: 'vaca', categories: ['animals'] },
      xPercent: 16,
      yPercent: 47,
      variant: 'berry',
      motion: 'sway',
      animationDelaySeconds: -1.4,
      animationDurationSeconds: 7.7,
    },
    {
      id: 'spawn-queso',
      word: { id: 'queso', text: 'queso', categories: ['food'] },
      xPercent: 77,
      yPercent: 38,
      variant: 'mint',
      motion: 'bob',
      animationDelaySeconds: -2.6,
      animationDurationSeconds: 6.4,
    },
    {
      id: 'spawn-pato',
      word: { id: 'pato', text: 'pato', categories: ['animals'] },
      xPercent: 39,
      yPercent: 27,
      variant: 'sun',
      motion: 'drift',
      animationDelaySeconds: -0.9,
      animationDurationSeconds: 6.9,
    },
    {
      id: 'spawn-ventana',
      word: { id: 'ventana', text: 'ventana', categories: ['home'] },
      xPercent: 64,
      yPercent: 48,
      variant: 'lavender',
      motion: 'sway',
      animationDelaySeconds: -1.9,
      animationDurationSeconds: 7.5,
    },
  ],
};
