import type { LevelDefinition } from '../../../types/gameplay';

export const FIRST_LEVEL: LevelDefinition = {
  id: 'animals-1',
  number: 1,
  title: 'ANIMALES',
  targetCategory: 'animals',
  targetCount: 20,
  initialCreatures: [
    {
      id: 'creature-gato',
      word: { id: 'gato', text: 'gato', categories: ['animals'] },
      xPercent: 18,
      yPercent: 25,
      variant: 'mint',
      motion: 'bob',
      animationDelaySeconds: -1.2,
      animationDurationSeconds: 5.8,
    },
    {
      id: 'creature-mesa',
      word: { id: 'mesa', text: 'mesa', categories: ['home'] },
      xPercent: 57,
      yPercent: 19,
      variant: 'berry',
      motion: 'sway',
      animationDelaySeconds: -2.1,
      animationDurationSeconds: 7.2,
    },
    {
      id: 'creature-perro',
      word: { id: 'perro', text: 'perro', categories: ['animals'] },
      xPercent: 79,
      yPercent: 34,
      variant: 'sun',
      motion: 'drift',
      animationDelaySeconds: -0.8,
      animationDurationSeconds: 6.7,
    },
    {
      id: 'creature-caballo',
      word: { id: 'caballo', text: 'caballo', categories: ['animals'] },
      xPercent: 31,
      yPercent: 49,
      variant: 'lavender',
      motion: 'drift',
      animationDelaySeconds: -3.4,
      animationDurationSeconds: 7.6,
    },
    {
      id: 'creature-coche',
      word: { id: 'coche', text: 'coche', categories: ['transport'] },
      xPercent: 68,
      yPercent: 55,
      variant: 'mint',
      motion: 'bob',
      animationDelaySeconds: -2.8,
      animationDurationSeconds: 6.1,
    },
    {
      id: 'creature-pajaro',
      word: { id: 'pajaro', text: 'pájaro', categories: ['animals'] },
      xPercent: 43,
      yPercent: 67,
      variant: 'berry',
      motion: 'sway',
      animationDelaySeconds: -1.7,
      animationDurationSeconds: 7.9,
    },
  ],
};
